#! /usr/bin/env bash

echo "Ensuring we know all the latest tags …"
git pull

LAST_VER=`/usr/bin/env node -e "console.log(require('./package.json').version);"`
STEP=${1:--p}
case $STEP in
    -v)
        NEXT_VER=`npm version $2`
    ;;
    -M)
        NEXT_VER=`npm version major`
    ;;
    -m)
        NEXT_VER=`npm version minor`
    ;;
    *)
        NEXT_VER=`npm version patch`
    ;;
esac

git tag -d v$NEXT_VER

LOG="$(git log --pretty=format:" - %s (%H)" v$LAST_VER..HEAD)"
echo "$LOG"

read -p "Update from v$LAST_VER to $NEXT_VER? " -n 2 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo

    git diff

    git add package.json
    if [[ -f package-lock.json ]];
    then
        git add package-lock.json
    fi
    git commit -m "chore(release): $NEXT_VER"

    EMAIL="$(git config --local --get user.email)"

    if [ -z "$EMAIL" ]; then
        echo "Author email in local git config not defined!"
        echo "Set it via"
        echo "$ git config user.email \"user@example.com\""
        exit
    fi

    PGP_KEY="$(gpg --keyid-format LONG --with-colons --list-secret-keys $EMAIL | grep sec | awk -F : '{ print $5; }')"

    echo -e "Release $NEXT_VER\n\n$LOG" | git tag $NEXT_VER -s -u "$PGP_KEY" --file -

    git tag -v $NEXT_VER
    git push origin $NEXT_VER
    git push
fi
