#!/bin/bash

STEP=${1:--p}

LAST_VER=`git describe | awk -F - '{ print substr($1, 2); }'`
MAX_MAJOR=`echo $LAST_VER | awk -F . '{ print $1; }'`
MAX_MINOR=`echo $LAST_VER | awk -F . '{ print $2; }'`
MAX_PATCH=`echo $LAST_VER | awk -F . '{ print $3; }'`

case $STEP in
-M)
  NEXT_VER="`(expr $MAX_MAJOR + 1)`.0.0"
  ;;
-m)
  NEXT_VER="$MAX_MAJOR.`(expr $MAX_MINOR + 1)`.0"
  ;;
*)
  NEXT_VER="$MAX_MAJOR.$MAX_MINOR.`(expr $MAX_PATCH + 1)`"
  ;;
esac

function updatePackage() {
    if [ -f $1 ]; then
        sed -i -r -e "s/\"version\":\W+\"$LAST_VER\"/\"version\": \"$NEXT_VER\"/" $1
        git diff
    fi
}

function updateSetupPy() {
    if [ -f $1 ]; then
        sed -i -r -e "s/\"version\"=\W+\"$LAST_VER\"/\"version\"=\"$NEXT_VER\"/" $1
        git diff
    fi
}

function commitPackage() {
    if [ -f $1 ]; then
        git add $1
        git commit -m "Release v$NEXT_VER"
    fi
}

LOG=`git log --pretty=format:" - %s (%H)" v$LAST_VER..HEAD`
echo $LOG
updatePackage package.json
updatePackage composer.json
updateSetupPy setup.py

read -p "Update from v$LAST_VER to v$NEXT_VER? " -n 2 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo ""
    commitPackage package.json
    commitPackage composer.json
    commitPackage setup.py
    echo -e "Release v$NEXT_VER\n\n$LOG" | git tag v$NEXT_VER -s --file -
    git tag -v v$NEXT_VER
    git push origin v$NEXT_VER
    git push
else
    if [ -f "package.json" ]; then
        git checkout -- package.json
    fi
    if [ -f "composer.json" ]; then
        git checkout -- composer.json
    fi
fi
